backend:
  name: github
  repo: JesusGerardoAguiar/Felicia

media_folder: static/assets
public_folder: assets

collections:
  - name: Galeria
    label: Imagen
    folder: content/gallery
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: Image, label: Imagen, widget: image }